# Generated by Django 2.2.5 on 2019-09-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=25)),
                ('destination', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
